version: '3.9'
name: tp1

services:

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config/config.ini
        read_only: true

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:  
      - type: bind
        source: ./data/archive
        target: /data
        read_only: true
      - type: bind
        source: ./client/config.ini
        target: /config/config.ini
        read_only: true
    depends_on:
      - server

volumes:
  server-config:
    external: false
  client-config:
    external: false
  dataset:
    external: false

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
