version: '3.9'
name: tp1

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 15672:15672
    networks:
      - testing_net

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config/config.ini
        read_only: true

  data_distributor_processor:
    container_name: data_distributor_processor
    image: data_distributor_processor:latest
    entrypoint: python3 /main.py
    #restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - testing_net
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  weather_processor:
    container_name: weather_processor
    image: weather_processor_image:latest
    entrypoint: python3 /main.py
    #restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - testing_net
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:  
      - type: bind
        source: ./data/archive
        target: /data
        read_only: true
      - type: bind
        source: ./client/config.ini
        target: /config/config.ini
        read_only: true
    depends_on:
      - server

volumes:
  server-config:
    external: false
  client-config:
    external: false
  dataset:
    external: false

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
